import path from "node:path"; import os from "node:os"; import { pathToFileURL } from "node:url";
const pw = await import(pathToFileURL(path.join(os.tmpdir(),"xuyuan-pw-tools","node_modules","playwright","index.mjs")).href).catch(()=>import("playwright"));
const b = await pw.chromium.launch(); const p = await b.newPage({viewport:{width:1536,height:770}});
const errs = [];
p.on("pageerror", e => errs.push("PAGEERROR: "+e.message));
p.on("console", m => { if (m.type()==="error") errs.push("CONSOLE: "+m.text().slice(0,200)); });
await p.goto("http://localhost:3000", {waitUntil:"domcontentloaded"});
await p.waitForTimeout(1200); await p.screenshot({path:"audit-screenshots/selfcheck-1200.png"});
await p.waitForTimeout(1600); await p.screenshot({path:"audit-screenshots/selfcheck-2800.png"});
await p.waitForTimeout(2000); await p.screenshot({path:"audit-screenshots/selfcheck-4800.png"});
const state = await p.evaluate(() => ({ bodyOverflow: document.body.style.overflow, loaderInDom: !!document.querySelector("[style*='9999']"), canvas: !!document.querySelector("canvas") }));
console.log(JSON.stringify(state)); console.log(errs.slice(0,10).join("\n") || "no js errors");
await b.close();
